version: '3.11'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bloomzy-backend:dev
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["python", "run.py"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: bloomzy-frontend:dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    command: ["npx", "http-server", "dist", "-p", "8080"]
