services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bloomzy-backend:prod
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      # Exemple SQLite local (décommenter pour activer)
      # - SQLALCHEMY_DATABASE_URI=sqlite:///../bloomzy.db
      # Exemple MySQL (décommenter et adapter pour activer)
      # - SQLALCHEMY_DATABASE_URI=mysql://user:password@mysql/bloomzy_db
    ports:
      - "5080:5000"
    command: ["python", "run.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5080
    image: bloomzy-frontend:prod
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
