version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bloomzy-backend:dev
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    command: ["python", "run.py"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5001
    image: bloomzy-frontend:dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - "3000:8080"
    depends_on:
      - backend
