services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: bloomzy-backend:dev
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/bloomzy.db
      # Exemple MySQL (décommenter et adapter pour activer)
      # - SQLALCHEMY_DATABASE_URI=mysql://user:password@mysql/bloomzy_db
    ports:
      - "5080:5000"
    volumes:
      - ./backend:/app
      - bloomzy_sqlite_data:/data
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5080
    image: bloomzy-frontend:dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  bloomzy_sqlite_data:
